allow traefik config + hande volume generation
thecodingmachine/deeployer pull request #75
Opened 2020-07-17 09:32 UTC by mika1K

2020-07-20 14:21 UTC, Kharhamel requested changes
Tu as commité beaucoup de trucs qui ne doivent jamais l'être, fait attention!

2020-07-20 15:19 UTC, Kharhamel requested changes
à e

2020-07-20 15:19 UTC, Kharhamel commented on .vscode/settings.json
> +{
à enlever

2020-07-20 15:19 UTC, Kharhamel commented on build/logs/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
à enlever

2020-07-27 13:03 UTC, mika1K commented on .vscode/settings.json
> +{
My bad

2020-07-27 13:04 UTC, mika1K commented on build/logs/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
C'est bon, new MR :)

2020-08-17 14:23 UTC, merged