Improve/compose config
thecodingmachine/deeployer pull request #76
Opened 2020-08-21 10:42 UTC by mika1K

J'ajoute le support de la fonctionnalité "commands"  de docker-compose, j'ai opté pour l'option de les ajouter au niveau de section config sur deeployer.libsonnet  
`{
  "version": "1.0",
  "containers": {
      "traefik": {
        "image": "traefik:v2.2"
      }
    },
  "config": {
    "docker-compose": {
      "command": [
        "--api.insecure=true",
        "--api.dashboard=true",
        "--providers.docker",
        "--providers.docker.exposedByDefault=false",
        "--log.level=DEBUG",
        "--entryPoints.web.address=:80",
        "--entrypoints.other.address=:9000"
      ]
    }
  }
  }
`

2020-08-24 13:41 UTC, Kharhamel requested changes

2020-08-24 13:41 UTC, Kharhamel commented on build/logs/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
à enelver

2020-08-24 13:41 UTC, Kharhamel commented on lib/php/utils/ComposeFileGenerator.php
> +    public const TmpFilePath = '/tmp/deeployer.json';
pourquoi l'avoir renommer?

2020-08-24 13:41 UTC, Kharhamel commented on tests/php/ComposeFileGeneratorTest.php
> +        $this->assertEquals([
tu veux tester uniquement  la partie 'volumes' de la config créée, pas toute la config

2020-08-27 08:38 UTC, mika1K commented on lib/php/utils/ComposeFileGenerator.php
> +    public const TmpFilePath = '/tmp/deeployer.json';
Le fichier qui contient la config et qui se trouve dans /tmp et qui contient la config que tu veux récupérer  c'est deeployer.json  , j'ai cru comprendre que tu t'es trompé de nom de fichier ou ce n'est pas le cas ?

2020-08-27 08:43 UTC, moufmouf commented on lib/php/utils/ComposeFileGenerator.php
> +    public const TmpFilePath = '/tmp/deeployer.json';
Mmmm.... le but de ComposeFileGenerator, c'est de générer un fichier docker-compose temporaire.
Du coup, ça fait du sens d'appeler ce fichier `docker-compose.json`. Ce n'est pas le même fichier que /tmp/deeployer.json qui est un fichier temporaire qui contient le JSON généré par un éventuel fichier deeployer.libsonnet

2020-11-19 09:32 UTC, Kharhamel approved these changes

2020-11-19 09:32 UTC, Kharhamel commented on lib/php/utils/ComposeFileGenerator.php
> +use phpDocumentor\Reflection\Types\Boolean;
je suis 99% sûr que tu n'a pas besoin de ça

2020-11-19 09:36 UTC, merged